server {
    listen       ${PORT};
    server_name  _;

    root  /usr/share/nginx/html;
    index index.html;

    # SPA-reititys: kaikki polut palautetaan index.html:ään
    location / {
        try_files $uri $uri/ /index.html;
    }
}